export const data = [
  {
    id: 1,
    name: "Dr. Shruti Kedia",
    specialty: "Heart Specialist",
    rating: "97%",
    experience: "4 Years Experience",
    available: "Next Available",
    time: "10:00 AM tomorrow",
    liked: true,
  },
  {
    id: 2,
    name: "Dr. Watanamuk",
    specialty: "Tooth Dentist",
    rating: "91%",
    experience: "5 Years Experience",
    available: "Next Available",
    time: "11:00 AM tomorrow",
    liked: false,
  },
  {
    id: 3,
    name: "Dr. Crownower",
    specialty: "Tooth Dentist",
    rating: "94%",
    experience: "8 Years Experience",
    available: "Next Available",
    time: "12:00 PM tomorrow",
    liked: true,
  },
  {
    id: 4,
    name: "Dr. Balestra",
    specialty: "Tooth Dentist",
    rating: "89%",
    experience: "3 Years Experience",
    available: "Next Available",
    time: "02:00 PM tomorrow",
    liked: false,
  },
  {
    id: 5,
    name: "Dr. Balestra",
    specialty: "Tooth Dentist",
    rating: "89%",
    experience: "3 Years Experience",
    available: "Next Available",
    time: "02:00 PM tomorrow",
    liked: false,
  },
  {
    id: 6,
    name: "Dr. Balestra",
    specialty: "Tooth Dentist",
    rating: "89%",
    experience: "3 Years Experience",
    available: "Next Available",
    time: "02:00 PM tomorrow",
    liked: false,
  },
  {
    id: 7,
    name: "Dr. Balestra",
    specialty: "Tooth Dentist",
    rating: "89%",
    experience: "3 Years Experience",
    available: "Next Available",
    time: "02:00 PM tomorrow",
    liked: false,
  },
];