export const initialDoctors = [
  {
    id: 1,
    name: "Dr. Park Gyo-young",
    specialty: "Specialist Cardiologist",
    rating: 4.5,
    views: 2475,
    image: "/imgs/park.jpeg",
    favorite: true,
  },
  {
    id: 2,
    name: "Dr. Ether Wall",
    specialty: "Specialist Cancer",
    rating: 2.7,
    views: 2754,
    image: "/imgs/park2.jpeg",
    favorite: false,
  },
  {
    id: 3,
    name: "Dr. Mistry Brick",
    specialty: "Specialist Dentist",
    rating: 2.8,
    views: 2893,
    image: "/imgs/park3.jpeg",
    favorite: false,
  },
  {
    id: 4,
    name: "Dr. JJ Thomsan Don",
    specialty: "Specialist Cardiologist",
    rating: 2.8,
    views: 2821,
    image: "/imgs/jawad.jpg",
    favorite: true,
  },
  {
    id: 5,
    name: "Dr. Sweety Madam",
    specialty: "Specialist Neurologist",
    rating: 2.9,
    views: 3000,
    image: "/imgs/asrar.jpg",
    favorite: false,
  },
  {
    id: 6,
    name: "Dr. Phoman Singh",
    specialty: "Specialist Neurologist",
    rating: 1.2,
    views: 3000,
    image: "/imgs/phoman.jpg",
    favorite: false,
  },
  {
    id: 7,
    name: "Dr. Sobia Madam",
    specialty: "Hair Specialist",
    rating: "1.6",
    views: 3000,
    image: "/imgs/sobia.jpg",
    favorite: false,
  },
  {
    id: 8,
    name: "Dr. Shruti Kedia",
    specialty: "Heart Specialist",
    rating: "2.5",
    views: 3000,
    image: "/imgs/azeem.jpg",
    favorite: true,
  },
  {
    id: 9,
    name: "Dr. Sursri Mishra",
    specialty: "throat Specialist",
    rating: "1.1",
    views: 3000,
    image: "/imgs/sursri.jpg",
    favorite: false,
  },
  {
    id: 10,
    name: "Dr. Sheela ki Jawani",
    specialty: "making love Specialist",
    rating: "2.3",
    views: 3000,
    image: "/imgs/sweety.jpg",
    favorite: false,
  },
  {
    id: 11,
    name: "Dr. Johny Sins Jr.",
    specialty: "Brain Surgeon",
    rating: "2.0",
    views: 3000,
    image: "/imgs/jony.jpg",
    favorite: false,
  },
  {
    id: 12,
    name: "Dr. Adeela Pyari",
    specialty: "Face Surgeon",
    rating: "3.2",
    views: 3000,
    image: "/imgs/adeel.jpg",
    favorite: false,
  },
  {
    id: 13,
    name: "Dr. Kim-Jo-Won",
    specialty: "Tooth Dentist",
    rating: "2.1",
    views: 3000,
    image: "/imgs/kimjowon.jpeg",
    favorite: false,
  },
  {
    id: 14,
    name: "Dr. Crownower",
    specialty: "making love Specialist",
    rating: "2.4",
    views: 3000,
    image: "/imgs/roh.webp",
    favorite: false,
  },
  {
    id: 15,
    name: "Dr. Ozge Torer",
    specialty: "makeup Specialist",
    rating: "4.5",
    views: 3000,
    image: "/imgs/ozge.jpg",
    favorite: true,
  },
];